---
title: 'marmap Demonstration'
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Prerequisites
```{r}
install.packages("marmap")
library(marmap) # Calls package forward
```


## Calling data into R
```{r}
papoue <- getNOAA.bathy(lon1 = 140, lon2 = 155,
                        lat1 = -13, lat2 = 0, 
                        resolution = 10) #Pulls out longitude and latitude data, and the associated depths

summary(papoue) # Here we want to summarise and check the data 
```

##Plotting Bathymetric Data
```{r}
plot(papoue) #Here we want to create a rough plot of the bathymetric data
```

###Cleaning up the plot and making it more informative & accessible (the long way) 
```{r}
plot(papoue, image = TRUE) #Plots a heat map, using the built in color pallete
scaleBathy(papoue, deg = 2, x = "bottomleft", inset = 5) #Adds a scale in kilometers
```

```{r}
blues <- colorRampPalette(c("red","purple","blue",
"cadetblue1","white")) # Creates a custom color pallete 
plot(papoue, image = TRUE, bpal = blues(100)) # Applys color pallete to the map
```

```{r}
plot(papoue, image = TRUE, bpal = blues(100),
     deep = c(-9000, -3000, 0),
     shallow = c(-3000, -10, 0),
     step = c(1000, 1000, 0),
     lwd = c(0.8, 0.8, 1), lty = c(1, 1, 1),
     col = c("lightgrey", "darkgrey", "black"),
     drawlabel = c(FALSE, FALSE, FALSE)) 
#Makes map less croweded by fixing some of the outlines and changing contrast
```


###Cleaning up the plot to produce publication-quality maps 
```{r}
blues <- c("lightsteelblue4", "lightsteelblue3",
"lightsteelblue2", "lightsteelblue1") # Creates a custom color palette of blues

plot(papoue, image = TRUE, land = TRUE, lwd = 0.1,
bpal = list(c(0, max(papoue), "grey"),
c(min(papoue),0,blues))) # Plotting the bathymetry with different colors for land and sea

plot(papoue, deep = 0, shallow = 0, step = 0,
lwd = 0.4, add = TRUE) # Making the coastline more visible
```
